/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.

Environment:

    Kernel-mode Driver Framework

--*/

#include "driver.h"
#include "device.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, SwitchDriverCreateDevice)
#pragma alloc_text (PAGE, SwitchDriverEvtDevicePrepareHardware)
#pragma alloc_text (PAGE, SendUrb)
#endif

#define DOS_DEVICE_NAME L"\\DosDevices\\VirtualXbox"


NTSTATUS
SwitchDriverCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
)
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_PNPPOWER_EVENT_CALLBACKS pnpPowerCallbacks;
    WDF_OBJECT_ATTRIBUTES   deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    WDFDEVICE device;
    NTSTATUS status;

    PAGED_CODE();

    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpPowerCallbacks);
    pnpPowerCallbacks.EvtDevicePrepareHardware = SwitchDriverEvtDevicePrepareHardware;
    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnpPowerCallbacks);

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (NT_SUCCESS(status)) {
        //
        // Get a pointer to the device context structure that we just associated
        // with the device object. We define this structure in the device.h
        // header file. DeviceGetContext is an inline function generated by
        // using the WDF_DECLARE_CONTEXT_TYPE_WITH_NAME macro in device.h.
        // This function will do the type checking and return the device context.
        // If you pass a wrong object handle it will return NULL and assert if
        // run under framework verifier mode.
        //
        deviceContext = DeviceGetContext(device);

        //
        // Create a device interface so that applications can find and talk
        // to us.
        //
        status = WdfDeviceCreateDeviceInterface(
            device,
            &GUID_DEVINTERFACE_SwitchDriver,
            NULL // ReferenceString
        );

        if (NT_SUCCESS(status)) {
            //
            // Initialize the I/O Package and any Queues
            //
            status = SwitchDriverQueueInitialize(device);
        }
    }
    return status;
}

NTSTATUS
SwitchDriverEvtDevicePrepareHardware(
    _In_ WDFDEVICE Device,
    _In_ WDFCMRESLIST ResourceList,
    _In_ WDFCMRESLIST ResourceListTranslated
)
/*++

Routine Description:

    In this callback, the driver does whatever is necessary to make the
    hardware ready to use.  In the case of a USB device, this involves
    reading and selecting descriptors.

Arguments:

    Device - handle to a device

Return Value:

    NT status value

--*/
{
    NTSTATUS status;
    PDEVICE_CONTEXT pDeviceContext;
    WDF_USB_DEVICE_CREATE_CONFIG createParams;
    WDF_USB_DEVICE_SELECT_CONFIG_PARAMS configParams;

    WDFUSBINTERFACE UsbInterface;
    BYTE numPipes;

    // iterator for pipes
    BYTE i;

    WDFMEMORY readMemory;

    WDFMEMORY transferMemory;
    PUCHAR transferBuffer;
    PUCHAR readBuffer;

    WDF_MEMORY_DESCRIPTOR readBufDesc;
    ULONG BytesRead;

    WDFIOTARGET ioTarget;
    WDF_IO_TARGET_OPEN_PARAMS openParams;

    UNREFERENCED_PARAMETER(ResourceList);
    UNREFERENCED_PARAMETER(ResourceListTranslated);

    PAGED_CODE();

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "%!FUNC! Entry");

    status = STATUS_SUCCESS;
    pDeviceContext = DeviceGetContext(Device);

    //
    // Create a USB device handle so that we can communicate with the
    // underlying USB stack. The WDFUSBDEVICE handle is used to query,
    // configure, and manage all aspects of the USB device.
    // These aspects include device properties, bus properties,
    // and I/O creation and synchronization. We only create the device the first time
    // PrepareHardware is called. If the device is restarted by pnp manager
    // for resource rebalance, we will use the same device handle but then select
    // the interfaces again because the USB stack could reconfigure the device on
    // restart.
    //
    if (pDeviceContext->UsbDevice == NULL) {

        //
        // Specifying a client contract version of 602 enables us to query for
        // and use the new capabilities of the USB driver stack for Windows 8.
        // It also implies that we conform to rules mentioned in MSDN
        // documentation for WdfUsbTargetDeviceCreateWithParameters.
        //
        WDF_USB_DEVICE_CREATE_CONFIG_INIT(&createParams,
            USBD_CLIENT_CONTRACT_VERSION_602
        );

        status = WdfUsbTargetDeviceCreateWithParameters(Device,
            &createParams,
            WDF_NO_OBJECT_ATTRIBUTES,
            &pDeviceContext->UsbDevice
        );

        if (!NT_SUCCESS(status)) {
            TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
                "WdfUsbTargetDeviceCreateWithParameters failed 0x%x", status);
            return status;
        }
    }

    //
    // Select the first configuration of the device, using the first alternate
    // setting of each interface
    //
    WDF_USB_DEVICE_SELECT_CONFIG_PARAMS_INIT_MULTIPLE_INTERFACES(&configParams,
        0,
        NULL
    );
    status = WdfUsbTargetDeviceSelectConfig(pDeviceContext->UsbDevice,
        WDF_NO_OBJECT_ATTRIBUTES,
        &configParams
    );

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfUsbTargetDeviceSelectConfig failed 0x%x", status);
        return status;
    }

    UsbInterface = WdfUsbTargetDeviceGetInterface(pDeviceContext->UsbDevice, 0);
    numPipes = WdfUsbInterfaceGetNumConfiguredPipes(UsbInterface);
    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "%d pipes", numPipes);

    if (numPipes != 2) {
        TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "Does not have exactly 2 pipes. \
                                                            May not be a genuine Switch Pro Controller");
        // TODO: filler, define custom status code
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    for (i = 0; i < numPipes; i++) {
        WDFUSBPIPE pipe;
        pipe = WdfUsbInterfaceGetConfiguredPipe(
            UsbInterface,
            i,
            NULL
        );

        if (WdfUsbTargetPipeGetType(pipe) == WdfUsbPipeTypeInterrupt) {
            if (WdfUsbTargetPipeIsOutEndpoint(pipe)) {
                if (pDeviceContext->InterruptOutPipe == NULL) {
                    pDeviceContext->InterruptOutPipe = pipe;
                }
                else {
                    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "Interrupt out pipe \
                                                                        already set");
                }
            }
            else if (WdfUsbTargetPipeIsInEndpoint(pipe)) {
                if (pDeviceContext->InterruptInPipe == NULL) {
                    pDeviceContext->InterruptInPipe = pipe;
                }
                else {
                    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "Interrupt in pipe \
                                                                        already set");
                }
            }
            else {
                TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "Unknown pipe type");
            }
        }
        else {
            TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "Not an interrupt pipe. \
                                                                May not be a genuine Switch Pro Controller");
            // TODO: filler, define custom status code
            return STATUS_INSUFFICIENT_RESOURCES;
        }
    }

    if (pDeviceContext->InterruptOutPipe == NULL) {
        TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "No interrupt out pipe");

        // TODO: filler, define custom status code
        return STATUS_INSUFFICIENT_RESOURCES;
    }
    if (pDeviceContext->InterruptInPipe == NULL) {
        TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "No interrupt in pipe");

        // TODO: filler, define custom status code
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    // Set up IO target for VirtualXbox Driver
    status = WdfIoTargetCreate(Device,
        WDF_NO_OBJECT_ATTRIBUTES,
        &ioTarget);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfIoTargetCreate failed 0x%x", status);
        return status;
    }

    DECLARE_CONST_UNICODE_STRING(dosDeviceName, DOS_DEVICE_NAME);

    WDF_IO_TARGET_OPEN_PARAMS_INIT_OPEN_BY_NAME(&openParams,
        &dosDeviceName,
        STANDARD_RIGHTS_ALL);

    status = WdfIoTargetOpen(ioTarget,
        &openParams);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfIoTargetOpen failed 0x%x", status);
        WdfObjectDelete(ioTarget);
        return status;
    }

    pDeviceContext->RemoteIoTarget = ioTarget;

    // Send handshake packet 0x80 0x02
    status = WdfMemoryCreate(WDF_NO_OBJECT_ATTRIBUTES,
        NonPagedPool,
        0,
        64,
        &transferMemory,
        NULL);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfMemoryCreate failed 0x%x", status);
        return status;
    }

    transferBuffer = (PUCHAR)WdfMemoryGetBuffer(transferMemory,
        NULL);

    RtlZeroMemory(transferBuffer, 64 * sizeof(UCHAR));
    memcpy(transferBuffer, "\x80\x02", 2);

    status = SendUrb(transferMemory, pDeviceContext);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "SendUrb failed 0x%x", status);
        return status;
    }

    // Read from pipe twice. First is 0x81 0x01. Second is 0x82 0x02
    status = WdfMemoryCreate(WDF_NO_OBJECT_ATTRIBUTES,
        NonPagedPool,
        0,
        64,
        &readMemory,
        NULL);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfMemoryCreate failed 0x%x", status);
        return status;
    }

    readBuffer = (PUCHAR)WdfMemoryGetBuffer(readMemory,
        NULL);

    WDF_MEMORY_DESCRIPTOR_INIT_BUFFER(&readBufDesc,
        readBuffer,
        64);

    status = WdfUsbTargetPipeReadSynchronously(pDeviceContext->InterruptInPipe,
        NULL,
        NULL,
        &readBufDesc,
        &BytesRead);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfUsbTargetPipeReadSynchronously failed 0x%x", status);
        return status;
    }

    status = WdfUsbTargetPipeReadSynchronously(pDeviceContext->InterruptInPipe,
        NULL,
        NULL,
        &readBufDesc,
        &BytesRead);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfUsbTargetPipeReadSynchronously failed 0x%x", status);
        return status;
    }

    // Set controller to USB mode only
    memcpy(transferBuffer, "\x80\x04", 2);

    status = SendUrb(transferMemory, pDeviceContext);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "SendUrb failed 0x%x", status);
        return status;
    }

    status = Controller_Init(Device);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "Controller_Init failed 0x%x", status);
        return status;
    }

    // TODO: Endless loop
    while (pDeviceContext->InterruptInPipe != NULL) {
        status = WdfUsbTargetPipeReadSynchronously(pDeviceContext->InterruptInPipe,
            NULL,
            NULL,
            &readBufDesc,
            &BytesRead);

        if (!NT_SUCCESS(status)) {
            TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
                "WdfUsbTargetPipeReadSynchronously failed 0x%x", status);
            return status;
        }
        Controller_Parse(Device, readBuffer);
        SendControllerData(Device);
    }

    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "%!FUNC! Exit");

    return status;
}


NTSTATUS SendUrb(
    _In_ WDFMEMORY transferMemory,
    _In_ PDEVICE_CONTEXT pDeviceContext
)
{
    NTSTATUS status;
    WDFMEMORY urbMemory;
    PURB urb;

    status = WdfMemoryCreate(WDF_NO_OBJECT_ATTRIBUTES,
        NonPagedPool,
        0,
        sizeof(struct _URB_BULK_OR_INTERRUPT_TRANSFER),
        &urbMemory,
        NULL);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfMemoryCreate failed 0x%x", status);
        return status;
    }

    urb = (PURB)WdfMemoryGetBuffer(urbMemory,
        NULL);

    UsbBuildInterruptOrBulkTransferRequest(urb,
        sizeof(struct _URB_BULK_OR_INTERRUPT_TRANSFER),
        WdfUsbTargetPipeWdmGetPipeHandle(pDeviceContext->InterruptOutPipe),
        WdfMemoryGetBuffer(transferMemory, NULL),
        NULL,
        64,
        0,
        NULL);

    status = WdfUsbTargetDeviceSendUrbSynchronously(pDeviceContext->UsbDevice,
        NULL,
        NULL,
        urb);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfUsbTargetPipeSendUrbSynchrounsly failed 0x%x", status);
        return status;
    }

    return status;
}

NTSTATUS SendControllerData(
    WDFDEVICE Device
)
{
    NTSTATUS status;
    WDFREQUEST request;
    WDFMEMORY memory;
    PUCHAR buffer;

    PCONTROLLER_CONTEXT pControllerContext;
    PDEVICE_CONTEXT pDeviceContext;

    BOOLEAN requestStatus;

    pControllerContext = ControllerGetContext(Device);
    pDeviceContext = DeviceGetContext(Device);

    status = WdfMemoryCreate(WDF_NO_OBJECT_ATTRIBUTES,
        NonPagedPool,
        0,
        20,
        &memory,
        NULL);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfMemoryCreate failed 0x%x", status);
        return status;
    }

    buffer = (PUCHAR)WdfMemoryGetBuffer(memory,
        NULL);

    RtlZeroMemory(buffer, 20 * sizeof(UCHAR));

    *(buffer) = 0x00;
    *(buffer + 1) = 0x14;
    *(buffer + 2) = (pControllerContext->bRightThumb << 7)
        | (pControllerContext->bLeftThumb << 6)
        | (pControllerContext->bMinus << 5)
        | (pControllerContext->bPlus << 4)
        | (pControllerContext->bDpadRight << 3)
        | (pControllerContext->bDpadLeft << 2)
        | (pControllerContext->bDpadDown << 1)
        | (pControllerContext->bDpadUp);
    *(buffer + 3) = (pControllerContext->bY << 7)
        | (pControllerContext->bX << 6)
        | (pControllerContext->bB << 5)
        | (pControllerContext->bA << 4)
        | (pControllerContext->bHome << 2)
        | (pControllerContext->bR << 1)
        | (pControllerContext->bL);
    *(buffer + 4) = (pControllerContext->bZL) == 1 ? 0xFF : 0x0;
    *(buffer + 5) = (pControllerContext->bZR) == 1 ? 0xFF : 0x0;
    *(buffer + 6) = (pControllerContext->sThumbLX) & 0xFF;
    *(buffer + 7) = ((pControllerContext->sThumbLX) & 0xFF00) >> 8;
    *(buffer + 8) = (pControllerContext->sThumbLY) & 0xFF;
    *(buffer + 9) = ((pControllerContext->sThumbLY) & 0xFF00) >> 8;
    *(buffer + 10) = (pControllerContext->sThumbRX) & 0xFF;
    *(buffer + 11) = ((pControllerContext->sThumbRX) & 0xFF00) >> 8;
    *(buffer + 12) = (pControllerContext->sThumbRY) & 0xFF;
    *(buffer + 13) = ((pControllerContext->sThumbRY) & 0xFF00) >> 8;

    status = WdfRequestCreate(WDF_NO_OBJECT_ATTRIBUTES,
        pDeviceContext->RemoteIoTarget,
        &request);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfRequestCreate failed 0x%x", status);
        return status;
    }

    status = WdfIoTargetFormatRequestForWrite(pDeviceContext->RemoteIoTarget,
        request,
        memory,
        NULL,
        NULL);

    if (!NT_SUCCESS(status)) {
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfIoTargetFormatRequestForWrite failed 0x%x", status);
        return status;
    }

    requestStatus = WdfRequestSend(request,
        pDeviceContext->RemoteIoTarget,
        WDF_NO_SEND_OPTIONS);

    if (requestStatus == FALSE)
    {
        status = WdfRequestGetStatus(request);
        WdfRequestComplete(request, status);
        TraceEvents(TRACE_LEVEL_ERROR, TRACE_DEVICE,
            "WdfRequestSend failed 0x%x", status);
    }

    return status;
}